//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WebServices.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.mosaicsoftware.co.uk/services/", ConfigurationName="ServiceReference2.PostcodeIT_UKSoap")]
    public interface PostcodeIT_UKSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/SetAddressStyle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginSetAddressStyle(WebServices.ServiceReference2.AddressStyle style, System.AsyncCallback callback, object asyncState);
        
        void EndSetAddressStyle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/GetByPostcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetByPostcode(string postcode, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.PafAddressResponse EndGetByPostcode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/GetByPostcodeSimple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetByPostcodeSimple(string postcode, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.SimpleAddressResponse EndGetByPostcodeSimple(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/GetByPostcodeSimpleFiltered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetByPostcodeSimpleFiltered(string postcode, string premises, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.SimpleAddressResponse EndGetByPostcodeSimpleFiltered(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/GetByPostcodeFiltered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetByPostcodeFiltered(string postcode, string premises, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.PafAddressResponse EndGetByPostcodeFiltered(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/GetByAddressKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetByAddressKey(int key, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.PafAddressResponse EndGetByAddressKey(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/GetByPostcode_Dataset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetByPostcode_Dataset(string postcode, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.ArrayOfXElement EndGetByPostcode_Dataset(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/CleanUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginCleanUp(string address1, string address2, string address3, string address4, string organisation, System.AsyncCallback callback, object asyncState);
        
        WebServices.ServiceReference2.PafAddressResponse EndCleanUp(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.mosaicsoftware.co.uk/services/LicenceCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginLicenceCount(System.AsyncCallback callback, object asyncState);
        
        int EndLicenceCount(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public enum AddressStyle {
        
        /// <remarks/>
        DEFAULT,
        
        /// <remarks/>
        UPPERCASE,
        
        /// <remarks/>
        LOWERCASE,
        
        /// <remarks/>
        FIRSTUPPER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public partial class PafAddressResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string resultMessageField;
        
        private PafAddress[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public PafAddress[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public partial class PafAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string postcodeField;
        
        private string departmentNameField;
        
        private string organisationNameField;
        
        private int buildingNumberField;
        
        private string buildingNameField;
        
        private string subBuildingNameField;
        
        private string streetNameField;
        
        private string thoroughfareNameField;
        
        private string thoroughfareDescriptorField;
        
        private string postTownField;
        
        private string dependentLocalityField;
        
        private string doubleDependentLocalityField;
        
        private int addressKeyField;
        
        private int numberOfHouseholdsField;
        
        private PafAddressSummary cSVField;
        
        private string[] summary2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
                this.RaisePropertyChanged("DepartmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrganisationName {
            get {
                return this.organisationNameField;
            }
            set {
                this.organisationNameField = value;
                this.RaisePropertyChanged("OrganisationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
                this.RaisePropertyChanged("BuildingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
                this.RaisePropertyChanged("BuildingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubBuildingName {
            get {
                return this.subBuildingNameField;
            }
            set {
                this.subBuildingNameField = value;
                this.RaisePropertyChanged("SubBuildingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ThoroughfareName {
            get {
                return this.thoroughfareNameField;
            }
            set {
                this.thoroughfareNameField = value;
                this.RaisePropertyChanged("ThoroughfareName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ThoroughfareDescriptor {
            get {
                return this.thoroughfareDescriptorField;
            }
            set {
                this.thoroughfareDescriptorField = value;
                this.RaisePropertyChanged("ThoroughfareDescriptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PostTown {
            get {
                return this.postTownField;
            }
            set {
                this.postTownField = value;
                this.RaisePropertyChanged("PostTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DependentLocality {
            get {
                return this.dependentLocalityField;
            }
            set {
                this.dependentLocalityField = value;
                this.RaisePropertyChanged("DependentLocality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DoubleDependentLocality {
            get {
                return this.doubleDependentLocalityField;
            }
            set {
                this.doubleDependentLocalityField = value;
                this.RaisePropertyChanged("DoubleDependentLocality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int AddressKey {
            get {
                return this.addressKeyField;
            }
            set {
                this.addressKeyField = value;
                this.RaisePropertyChanged("AddressKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int NumberOfHouseholds {
            get {
                return this.numberOfHouseholdsField;
            }
            set {
                this.numberOfHouseholdsField = value;
                this.RaisePropertyChanged("NumberOfHouseholds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public PafAddressSummary CSV {
            get {
                return this.cSVField;
            }
            set {
                this.cSVField = value;
                this.RaisePropertyChanged("CSV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public string[] Summary2 {
            get {
                return this.summary2Field;
            }
            set {
                this.summary2Field = value;
                this.RaisePropertyChanged("Summary2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public partial class PafAddressSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int addressKeyField;
        
        private string summaryAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AddressKey {
            get {
                return this.addressKeyField;
            }
            set {
                this.addressKeyField = value;
                this.RaisePropertyChanged("AddressKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SummaryAddress {
            get {
                return this.summaryAddressField;
            }
            set {
                this.summaryAddressField = value;
                this.RaisePropertyChanged("SummaryAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public partial class SimpleAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int addressKeyField;
        
        private string departmentNameField;
        
        private string organisationNameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string address4Field;
        
        private string address5Field;
        
        private string postTownField;
        
        private string postcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AddressKey {
            get {
                return this.addressKeyField;
            }
            set {
                this.addressKeyField = value;
                this.RaisePropertyChanged("AddressKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
                this.RaisePropertyChanged("DepartmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrganisationName {
            get {
                return this.organisationNameField;
            }
            set {
                this.organisationNameField = value;
                this.RaisePropertyChanged("OrganisationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("Address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address4 {
            get {
                return this.address4Field;
            }
            set {
                this.address4Field = value;
                this.RaisePropertyChanged("Address4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Address5 {
            get {
                return this.address5Field;
            }
            set {
                this.address5Field = value;
                this.RaisePropertyChanged("Address5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostTown {
            get {
                return this.postTownField;
            }
            set {
                this.postTownField = value;
                this.RaisePropertyChanged("PostTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public partial class SimpleAddressResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string resultMessageField;
        
        private SimpleAddress[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public SimpleAddress[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.mosaicsoftware.co.uk/services/")]
    public partial class PostcodeITHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIdField;
        
        private string licenceKeyField;
        
        private string machineIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LicenceKey {
            get {
                return this.licenceKeyField;
            }
            set {
                this.licenceKeyField = value;
                this.RaisePropertyChanged("LicenceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MachineId {
            get {
                return this.machineIdField;
            }
            set {
                this.machineIdField = value;
                this.RaisePropertyChanged("MachineId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostcodeIT_UKSoapChannel : WebServices.ServiceReference2.PostcodeIT_UKSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByPostcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByPostcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.PafAddressResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.PafAddressResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByPostcodeSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByPostcodeSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.SimpleAddressResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.SimpleAddressResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByPostcodeSimpleFilteredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByPostcodeSimpleFilteredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.SimpleAddressResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.SimpleAddressResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByPostcodeFilteredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByPostcodeFilteredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.PafAddressResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.PafAddressResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByAddressKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByAddressKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.PafAddressResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.PafAddressResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByPostcode_DatasetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByPostcode_DatasetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CleanUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CleanUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebServices.ServiceReference2.PafAddressResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebServices.ServiceReference2.PafAddressResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenceCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LicenceCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostcodeIT_UKSoapClient : System.ServiceModel.ClientBase<WebServices.ServiceReference2.PostcodeIT_UKSoap>, WebServices.ServiceReference2.PostcodeIT_UKSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetAddressStyleDelegate;
        
        private EndOperationDelegate onEndSetAddressStyleDelegate;
        
        private System.Threading.SendOrPostCallback onSetAddressStyleCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByPostcodeDelegate;
        
        private EndOperationDelegate onEndGetByPostcodeDelegate;
        
        private System.Threading.SendOrPostCallback onGetByPostcodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByPostcodeSimpleDelegate;
        
        private EndOperationDelegate onEndGetByPostcodeSimpleDelegate;
        
        private System.Threading.SendOrPostCallback onGetByPostcodeSimpleCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByPostcodeSimpleFilteredDelegate;
        
        private EndOperationDelegate onEndGetByPostcodeSimpleFilteredDelegate;
        
        private System.Threading.SendOrPostCallback onGetByPostcodeSimpleFilteredCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByPostcodeFilteredDelegate;
        
        private EndOperationDelegate onEndGetByPostcodeFilteredDelegate;
        
        private System.Threading.SendOrPostCallback onGetByPostcodeFilteredCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByAddressKeyDelegate;
        
        private EndOperationDelegate onEndGetByAddressKeyDelegate;
        
        private System.Threading.SendOrPostCallback onGetByAddressKeyCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByPostcode_DatasetDelegate;
        
        private EndOperationDelegate onEndGetByPostcode_DatasetDelegate;
        
        private System.Threading.SendOrPostCallback onGetByPostcode_DatasetCompletedDelegate;
        
        private BeginOperationDelegate onBeginCleanUpDelegate;
        
        private EndOperationDelegate onEndCleanUpDelegate;
        
        private System.Threading.SendOrPostCallback onCleanUpCompletedDelegate;
        
        private BeginOperationDelegate onBeginLicenceCountDelegate;
        
        private EndOperationDelegate onEndLicenceCountDelegate;
        
        private System.Threading.SendOrPostCallback onLicenceCountCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PostcodeIT_UKSoapClient() {
        }
        
        public PostcodeIT_UKSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostcodeIT_UKSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostcodeIT_UKSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostcodeIT_UKSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetAddressStyleCompleted;
        
        public event System.EventHandler<GetByPostcodeCompletedEventArgs> GetByPostcodeCompleted;
        
        public event System.EventHandler<GetByPostcodeSimpleCompletedEventArgs> GetByPostcodeSimpleCompleted;
        
        public event System.EventHandler<GetByPostcodeSimpleFilteredCompletedEventArgs> GetByPostcodeSimpleFilteredCompleted;
        
        public event System.EventHandler<GetByPostcodeFilteredCompletedEventArgs> GetByPostcodeFilteredCompleted;
        
        public event System.EventHandler<GetByAddressKeyCompletedEventArgs> GetByAddressKeyCompleted;
        
        public event System.EventHandler<GetByPostcode_DatasetCompletedEventArgs> GetByPostcode_DatasetCompleted;
        
        public event System.EventHandler<CleanUpCompletedEventArgs> CleanUpCompleted;
        
        public event System.EventHandler<LicenceCountCompletedEventArgs> LicenceCountCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WebServices.ServiceReference2.PostcodeIT_UKSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginSetAddressStyle(WebServices.ServiceReference2.AddressStyle style, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetAddressStyle(style, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WebServices.ServiceReference2.PostcodeIT_UKSoap.EndSetAddressStyle(System.IAsyncResult result) {
            base.Channel.EndSetAddressStyle(result);
        }
        
        private System.IAsyncResult OnBeginSetAddressStyle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WebServices.ServiceReference2.AddressStyle style = ((WebServices.ServiceReference2.AddressStyle)(inValues[0]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginSetAddressStyle(style, callback, asyncState);
        }
        
        private object[] OnEndSetAddressStyle(System.IAsyncResult result) {
            ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndSetAddressStyle(result);
            return null;
        }
        
        private void OnSetAddressStyleCompleted(object state) {
            if ((this.SetAddressStyleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetAddressStyleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetAddressStyleAsync(WebServices.ServiceReference2.AddressStyle style) {
            this.SetAddressStyleAsync(style, null);
        }
        
        public void SetAddressStyleAsync(WebServices.ServiceReference2.AddressStyle style, object userState) {
            if ((this.onBeginSetAddressStyleDelegate == null)) {
                this.onBeginSetAddressStyleDelegate = new BeginOperationDelegate(this.OnBeginSetAddressStyle);
            }
            if ((this.onEndSetAddressStyleDelegate == null)) {
                this.onEndSetAddressStyleDelegate = new EndOperationDelegate(this.OnEndSetAddressStyle);
            }
            if ((this.onSetAddressStyleCompletedDelegate == null)) {
                this.onSetAddressStyleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetAddressStyleCompleted);
            }
            base.InvokeAsync(this.onBeginSetAddressStyleDelegate, new object[] {
                        style}, this.onEndSetAddressStyleDelegate, this.onSetAddressStyleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginGetByPostcode(string postcode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByPostcode(postcode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.PafAddressResponse WebServices.ServiceReference2.PostcodeIT_UKSoap.EndGetByPostcode(System.IAsyncResult result) {
            return base.Channel.EndGetByPostcode(result);
        }
        
        private System.IAsyncResult OnBeginGetByPostcode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string postcode = ((string)(inValues[0]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginGetByPostcode(postcode, callback, asyncState);
        }
        
        private object[] OnEndGetByPostcode(System.IAsyncResult result) {
            WebServices.ServiceReference2.PafAddressResponse retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndGetByPostcode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByPostcodeCompleted(object state) {
            if ((this.GetByPostcodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByPostcodeCompleted(this, new GetByPostcodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByPostcodeAsync(string postcode) {
            this.GetByPostcodeAsync(postcode, null);
        }
        
        public void GetByPostcodeAsync(string postcode, object userState) {
            if ((this.onBeginGetByPostcodeDelegate == null)) {
                this.onBeginGetByPostcodeDelegate = new BeginOperationDelegate(this.OnBeginGetByPostcode);
            }
            if ((this.onEndGetByPostcodeDelegate == null)) {
                this.onEndGetByPostcodeDelegate = new EndOperationDelegate(this.OnEndGetByPostcode);
            }
            if ((this.onGetByPostcodeCompletedDelegate == null)) {
                this.onGetByPostcodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByPostcodeCompleted);
            }
            base.InvokeAsync(this.onBeginGetByPostcodeDelegate, new object[] {
                        postcode}, this.onEndGetByPostcodeDelegate, this.onGetByPostcodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginGetByPostcodeSimple(string postcode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByPostcodeSimple(postcode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.SimpleAddressResponse WebServices.ServiceReference2.PostcodeIT_UKSoap.EndGetByPostcodeSimple(System.IAsyncResult result) {
            return base.Channel.EndGetByPostcodeSimple(result);
        }
        
        private System.IAsyncResult OnBeginGetByPostcodeSimple(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string postcode = ((string)(inValues[0]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginGetByPostcodeSimple(postcode, callback, asyncState);
        }
        
        private object[] OnEndGetByPostcodeSimple(System.IAsyncResult result) {
            WebServices.ServiceReference2.SimpleAddressResponse retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndGetByPostcodeSimple(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByPostcodeSimpleCompleted(object state) {
            if ((this.GetByPostcodeSimpleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByPostcodeSimpleCompleted(this, new GetByPostcodeSimpleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByPostcodeSimpleAsync(string postcode) {
            this.GetByPostcodeSimpleAsync(postcode, null);
        }
        
        public void GetByPostcodeSimpleAsync(string postcode, object userState) {
            if ((this.onBeginGetByPostcodeSimpleDelegate == null)) {
                this.onBeginGetByPostcodeSimpleDelegate = new BeginOperationDelegate(this.OnBeginGetByPostcodeSimple);
            }
            if ((this.onEndGetByPostcodeSimpleDelegate == null)) {
                this.onEndGetByPostcodeSimpleDelegate = new EndOperationDelegate(this.OnEndGetByPostcodeSimple);
            }
            if ((this.onGetByPostcodeSimpleCompletedDelegate == null)) {
                this.onGetByPostcodeSimpleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByPostcodeSimpleCompleted);
            }
            base.InvokeAsync(this.onBeginGetByPostcodeSimpleDelegate, new object[] {
                        postcode}, this.onEndGetByPostcodeSimpleDelegate, this.onGetByPostcodeSimpleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginGetByPostcodeSimpleFiltered(string postcode, string premises, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByPostcodeSimpleFiltered(postcode, premises, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.SimpleAddressResponse WebServices.ServiceReference2.PostcodeIT_UKSoap.EndGetByPostcodeSimpleFiltered(System.IAsyncResult result) {
            return base.Channel.EndGetByPostcodeSimpleFiltered(result);
        }
        
        private System.IAsyncResult OnBeginGetByPostcodeSimpleFiltered(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string postcode = ((string)(inValues[0]));
            string premises = ((string)(inValues[1]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginGetByPostcodeSimpleFiltered(postcode, premises, callback, asyncState);
        }
        
        private object[] OnEndGetByPostcodeSimpleFiltered(System.IAsyncResult result) {
            WebServices.ServiceReference2.SimpleAddressResponse retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndGetByPostcodeSimpleFiltered(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByPostcodeSimpleFilteredCompleted(object state) {
            if ((this.GetByPostcodeSimpleFilteredCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByPostcodeSimpleFilteredCompleted(this, new GetByPostcodeSimpleFilteredCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByPostcodeSimpleFilteredAsync(string postcode, string premises) {
            this.GetByPostcodeSimpleFilteredAsync(postcode, premises, null);
        }
        
        public void GetByPostcodeSimpleFilteredAsync(string postcode, string premises, object userState) {
            if ((this.onBeginGetByPostcodeSimpleFilteredDelegate == null)) {
                this.onBeginGetByPostcodeSimpleFilteredDelegate = new BeginOperationDelegate(this.OnBeginGetByPostcodeSimpleFiltered);
            }
            if ((this.onEndGetByPostcodeSimpleFilteredDelegate == null)) {
                this.onEndGetByPostcodeSimpleFilteredDelegate = new EndOperationDelegate(this.OnEndGetByPostcodeSimpleFiltered);
            }
            if ((this.onGetByPostcodeSimpleFilteredCompletedDelegate == null)) {
                this.onGetByPostcodeSimpleFilteredCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByPostcodeSimpleFilteredCompleted);
            }
            base.InvokeAsync(this.onBeginGetByPostcodeSimpleFilteredDelegate, new object[] {
                        postcode,
                        premises}, this.onEndGetByPostcodeSimpleFilteredDelegate, this.onGetByPostcodeSimpleFilteredCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginGetByPostcodeFiltered(string postcode, string premises, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByPostcodeFiltered(postcode, premises, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.PafAddressResponse WebServices.ServiceReference2.PostcodeIT_UKSoap.EndGetByPostcodeFiltered(System.IAsyncResult result) {
            return base.Channel.EndGetByPostcodeFiltered(result);
        }
        
        private System.IAsyncResult OnBeginGetByPostcodeFiltered(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string postcode = ((string)(inValues[0]));
            string premises = ((string)(inValues[1]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginGetByPostcodeFiltered(postcode, premises, callback, asyncState);
        }
        
        private object[] OnEndGetByPostcodeFiltered(System.IAsyncResult result) {
            WebServices.ServiceReference2.PafAddressResponse retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndGetByPostcodeFiltered(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByPostcodeFilteredCompleted(object state) {
            if ((this.GetByPostcodeFilteredCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByPostcodeFilteredCompleted(this, new GetByPostcodeFilteredCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByPostcodeFilteredAsync(string postcode, string premises) {
            this.GetByPostcodeFilteredAsync(postcode, premises, null);
        }
        
        public void GetByPostcodeFilteredAsync(string postcode, string premises, object userState) {
            if ((this.onBeginGetByPostcodeFilteredDelegate == null)) {
                this.onBeginGetByPostcodeFilteredDelegate = new BeginOperationDelegate(this.OnBeginGetByPostcodeFiltered);
            }
            if ((this.onEndGetByPostcodeFilteredDelegate == null)) {
                this.onEndGetByPostcodeFilteredDelegate = new EndOperationDelegate(this.OnEndGetByPostcodeFiltered);
            }
            if ((this.onGetByPostcodeFilteredCompletedDelegate == null)) {
                this.onGetByPostcodeFilteredCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByPostcodeFilteredCompleted);
            }
            base.InvokeAsync(this.onBeginGetByPostcodeFilteredDelegate, new object[] {
                        postcode,
                        premises}, this.onEndGetByPostcodeFilteredDelegate, this.onGetByPostcodeFilteredCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginGetByAddressKey(int key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByAddressKey(key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.PafAddressResponse WebServices.ServiceReference2.PostcodeIT_UKSoap.EndGetByAddressKey(System.IAsyncResult result) {
            return base.Channel.EndGetByAddressKey(result);
        }
        
        private System.IAsyncResult OnBeginGetByAddressKey(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int key = ((int)(inValues[0]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginGetByAddressKey(key, callback, asyncState);
        }
        
        private object[] OnEndGetByAddressKey(System.IAsyncResult result) {
            WebServices.ServiceReference2.PafAddressResponse retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndGetByAddressKey(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByAddressKeyCompleted(object state) {
            if ((this.GetByAddressKeyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByAddressKeyCompleted(this, new GetByAddressKeyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByAddressKeyAsync(int key) {
            this.GetByAddressKeyAsync(key, null);
        }
        
        public void GetByAddressKeyAsync(int key, object userState) {
            if ((this.onBeginGetByAddressKeyDelegate == null)) {
                this.onBeginGetByAddressKeyDelegate = new BeginOperationDelegate(this.OnBeginGetByAddressKey);
            }
            if ((this.onEndGetByAddressKeyDelegate == null)) {
                this.onEndGetByAddressKeyDelegate = new EndOperationDelegate(this.OnEndGetByAddressKey);
            }
            if ((this.onGetByAddressKeyCompletedDelegate == null)) {
                this.onGetByAddressKeyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByAddressKeyCompleted);
            }
            base.InvokeAsync(this.onBeginGetByAddressKeyDelegate, new object[] {
                        key}, this.onEndGetByAddressKeyDelegate, this.onGetByAddressKeyCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginGetByPostcode_Dataset(string postcode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetByPostcode_Dataset(postcode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.ArrayOfXElement WebServices.ServiceReference2.PostcodeIT_UKSoap.EndGetByPostcode_Dataset(System.IAsyncResult result) {
            return base.Channel.EndGetByPostcode_Dataset(result);
        }
        
        private System.IAsyncResult OnBeginGetByPostcode_Dataset(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string postcode = ((string)(inValues[0]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginGetByPostcode_Dataset(postcode, callback, asyncState);
        }
        
        private object[] OnEndGetByPostcode_Dataset(System.IAsyncResult result) {
            WebServices.ServiceReference2.ArrayOfXElement retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndGetByPostcode_Dataset(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByPostcode_DatasetCompleted(object state) {
            if ((this.GetByPostcode_DatasetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByPostcode_DatasetCompleted(this, new GetByPostcode_DatasetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByPostcode_DatasetAsync(string postcode) {
            this.GetByPostcode_DatasetAsync(postcode, null);
        }
        
        public void GetByPostcode_DatasetAsync(string postcode, object userState) {
            if ((this.onBeginGetByPostcode_DatasetDelegate == null)) {
                this.onBeginGetByPostcode_DatasetDelegate = new BeginOperationDelegate(this.OnBeginGetByPostcode_Dataset);
            }
            if ((this.onEndGetByPostcode_DatasetDelegate == null)) {
                this.onEndGetByPostcode_DatasetDelegate = new EndOperationDelegate(this.OnEndGetByPostcode_Dataset);
            }
            if ((this.onGetByPostcode_DatasetCompletedDelegate == null)) {
                this.onGetByPostcode_DatasetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByPostcode_DatasetCompleted);
            }
            base.InvokeAsync(this.onBeginGetByPostcode_DatasetDelegate, new object[] {
                        postcode}, this.onEndGetByPostcode_DatasetDelegate, this.onGetByPostcode_DatasetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginCleanUp(string address1, string address2, string address3, string address4, string organisation, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCleanUp(address1, address2, address3, address4, organisation, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ServiceReference2.PafAddressResponse WebServices.ServiceReference2.PostcodeIT_UKSoap.EndCleanUp(System.IAsyncResult result) {
            return base.Channel.EndCleanUp(result);
        }
        
        private System.IAsyncResult OnBeginCleanUp(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string address1 = ((string)(inValues[0]));
            string address2 = ((string)(inValues[1]));
            string address3 = ((string)(inValues[2]));
            string address4 = ((string)(inValues[3]));
            string organisation = ((string)(inValues[4]));
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginCleanUp(address1, address2, address3, address4, organisation, callback, asyncState);
        }
        
        private object[] OnEndCleanUp(System.IAsyncResult result) {
            WebServices.ServiceReference2.PafAddressResponse retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndCleanUp(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCleanUpCompleted(object state) {
            if ((this.CleanUpCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CleanUpCompleted(this, new CleanUpCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CleanUpAsync(string address1, string address2, string address3, string address4, string organisation) {
            this.CleanUpAsync(address1, address2, address3, address4, organisation, null);
        }
        
        public void CleanUpAsync(string address1, string address2, string address3, string address4, string organisation, object userState) {
            if ((this.onBeginCleanUpDelegate == null)) {
                this.onBeginCleanUpDelegate = new BeginOperationDelegate(this.OnBeginCleanUp);
            }
            if ((this.onEndCleanUpDelegate == null)) {
                this.onEndCleanUpDelegate = new EndOperationDelegate(this.OnEndCleanUp);
            }
            if ((this.onCleanUpCompletedDelegate == null)) {
                this.onCleanUpCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCleanUpCompleted);
            }
            base.InvokeAsync(this.onBeginCleanUpDelegate, new object[] {
                        address1,
                        address2,
                        address3,
                        address4,
                        organisation}, this.onEndCleanUpDelegate, this.onCleanUpCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServices.ServiceReference2.PostcodeIT_UKSoap.BeginLicenceCount(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLicenceCount(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int WebServices.ServiceReference2.PostcodeIT_UKSoap.EndLicenceCount(System.IAsyncResult result) {
            return base.Channel.EndLicenceCount(result);
        }
        
        private System.IAsyncResult OnBeginLicenceCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).BeginLicenceCount(callback, asyncState);
        }
        
        private object[] OnEndLicenceCount(System.IAsyncResult result) {
            int retVal = ((WebServices.ServiceReference2.PostcodeIT_UKSoap)(this)).EndLicenceCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLicenceCountCompleted(object state) {
            if ((this.LicenceCountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LicenceCountCompleted(this, new LicenceCountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LicenceCountAsync() {
            this.LicenceCountAsync(null);
        }
        
        public void LicenceCountAsync(object userState) {
            if ((this.onBeginLicenceCountDelegate == null)) {
                this.onBeginLicenceCountDelegate = new BeginOperationDelegate(this.OnBeginLicenceCount);
            }
            if ((this.onEndLicenceCountDelegate == null)) {
                this.onEndLicenceCountDelegate = new EndOperationDelegate(this.OnEndLicenceCount);
            }
            if ((this.onLicenceCountCompletedDelegate == null)) {
                this.onLicenceCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLicenceCountCompleted);
            }
            base.InvokeAsync(this.onBeginLicenceCountDelegate, null, this.onEndLicenceCountDelegate, this.onLicenceCountCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WebServices.ServiceReference2.PostcodeIT_UKSoap CreateChannel() {
            return new PostcodeIT_UKSoapClientChannel(this);
        }
        
        private class PostcodeIT_UKSoapClientChannel : ChannelBase<WebServices.ServiceReference2.PostcodeIT_UKSoap>, WebServices.ServiceReference2.PostcodeIT_UKSoap {
            
            public PostcodeIT_UKSoapClientChannel(System.ServiceModel.ClientBase<WebServices.ServiceReference2.PostcodeIT_UKSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetAddressStyle(WebServices.ServiceReference2.AddressStyle style, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = style;
                System.IAsyncResult _result = base.BeginInvoke("SetAddressStyle", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSetAddressStyle(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SetAddressStyle", _args, result);
            }
            
            public System.IAsyncResult BeginGetByPostcode(string postcode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = postcode;
                System.IAsyncResult _result = base.BeginInvoke("GetByPostcode", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.PafAddressResponse EndGetByPostcode(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.PafAddressResponse _result = ((WebServices.ServiceReference2.PafAddressResponse)(base.EndInvoke("GetByPostcode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByPostcodeSimple(string postcode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = postcode;
                System.IAsyncResult _result = base.BeginInvoke("GetByPostcodeSimple", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.SimpleAddressResponse EndGetByPostcodeSimple(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.SimpleAddressResponse _result = ((WebServices.ServiceReference2.SimpleAddressResponse)(base.EndInvoke("GetByPostcodeSimple", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByPostcodeSimpleFiltered(string postcode, string premises, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = postcode;
                _args[1] = premises;
                System.IAsyncResult _result = base.BeginInvoke("GetByPostcodeSimpleFiltered", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.SimpleAddressResponse EndGetByPostcodeSimpleFiltered(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.SimpleAddressResponse _result = ((WebServices.ServiceReference2.SimpleAddressResponse)(base.EndInvoke("GetByPostcodeSimpleFiltered", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByPostcodeFiltered(string postcode, string premises, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = postcode;
                _args[1] = premises;
                System.IAsyncResult _result = base.BeginInvoke("GetByPostcodeFiltered", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.PafAddressResponse EndGetByPostcodeFiltered(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.PafAddressResponse _result = ((WebServices.ServiceReference2.PafAddressResponse)(base.EndInvoke("GetByPostcodeFiltered", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByAddressKey(int key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = key;
                System.IAsyncResult _result = base.BeginInvoke("GetByAddressKey", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.PafAddressResponse EndGetByAddressKey(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.PafAddressResponse _result = ((WebServices.ServiceReference2.PafAddressResponse)(base.EndInvoke("GetByAddressKey", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetByPostcode_Dataset(string postcode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = postcode;
                System.IAsyncResult _result = base.BeginInvoke("GetByPostcode_Dataset", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.ArrayOfXElement EndGetByPostcode_Dataset(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.ArrayOfXElement _result = ((WebServices.ServiceReference2.ArrayOfXElement)(base.EndInvoke("GetByPostcode_Dataset", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCleanUp(string address1, string address2, string address3, string address4, string organisation, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = address1;
                _args[1] = address2;
                _args[2] = address3;
                _args[3] = address4;
                _args[4] = organisation;
                System.IAsyncResult _result = base.BeginInvoke("CleanUp", _args, callback, asyncState);
                return _result;
            }
            
            public WebServices.ServiceReference2.PafAddressResponse EndCleanUp(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebServices.ServiceReference2.PafAddressResponse _result = ((WebServices.ServiceReference2.PafAddressResponse)(base.EndInvoke("CleanUp", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLicenceCount(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("LicenceCount", _args, callback, asyncState);
                return _result;
            }
            
            public int EndLicenceCount(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("LicenceCount", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.Phone.ServiceReference", "3.7.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
