//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WCFTestApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dsetzer.27seconds.com/ws/", ConfigurationName="ServiceReference1.ArticlesSoap")]
    public interface ArticlesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dsetzer.27seconds.com/ws/GetArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.IAsyncResult BeginGetArticle(int articleId, System.AsyncCallback callback, object asyncState);
        
        WCFTestApp.ServiceReference1.ArrayOfXElement EndGetArticle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dsetzer.27seconds.com/ws/SearchArticles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.IAsyncResult BeginSearchArticles(object[] authorId, object[] articleApplicable, string articleTitle, string articleSummary, object[] articleKeywords, System.AsyncCallback callback, object asyncState);
        
        WCFTestApp.ServiceReference1.ArrayOfXElement EndSearchArticles(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dsetzer.27seconds.com/ws/RateArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.IAsyncResult BeginRateArticle(int articleId, int rating, System.AsyncCallback callback, object asyncState);
        
        WCFTestApp.ServiceReference1.ArrayOfXElement EndRateArticle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dsetzer.27seconds.com/ws/RateArticleWithComments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.IAsyncResult BeginRateArticle1(WCFTestApp.ServiceReference1.RateArticleWithComments request, System.AsyncCallback callback, object asyncState);
        
        WCFTestApp.ServiceReference1.RateArticleWithComments1 EndRateArticle1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dsetzer.27seconds.com/ws/GetArticleLookups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.IAsyncResult BeginGetArticleLookups(System.AsyncCallback callback, object asyncState);
        
        WCFTestApp.ServiceReference1.ArrayOfXElement EndGetArticleLookups(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dsetzer.27seconds.com/ws/GetArticleLookupsForArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.IAsyncResult BeginGetArticleLookups1(WCFTestApp.ServiceReference1.GetArticleLookupsForArticle request, System.AsyncCallback callback, object asyncState);
        
        WCFTestApp.ServiceReference1.GetArticleLookupsForArticle1 EndGetArticleLookups1(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RateArticleWithComments", WrapperNamespace="http://dsetzer.27seconds.com/ws/", IsWrapped=true)]
    public partial class RateArticleWithComments {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dsetzer.27seconds.com/ws/", Order=0)]
        public int articleId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dsetzer.27seconds.com/ws/", Order=1)]
        public int rating;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dsetzer.27seconds.com/ws/", Order=2)]
        public string comments;
        
        public RateArticleWithComments() {
        }
        
        public RateArticleWithComments(int articleId, int rating, string comments) {
            this.articleId = articleId;
            this.rating = rating;
            this.comments = comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RateArticleWithCommentsResponse", WrapperNamespace="http://dsetzer.27seconds.com/ws/", IsWrapped=true)]
    public partial class RateArticleWithComments1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dsetzer.27seconds.com/ws/", Order=0)]
        public WCFTestApp.ServiceReference1.ArrayOfXElement RateArticleWithCommentsResult;
        
        public RateArticleWithComments1() {
        }
        
        public RateArticleWithComments1(WCFTestApp.ServiceReference1.ArrayOfXElement RateArticleWithCommentsResult) {
            this.RateArticleWithCommentsResult = RateArticleWithCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArticleLookupsForArticle", WrapperNamespace="http://dsetzer.27seconds.com/ws/", IsWrapped=true)]
    public partial class GetArticleLookupsForArticle {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dsetzer.27seconds.com/ws/", Order=0)]
        public int articleId;
        
        public GetArticleLookupsForArticle() {
        }
        
        public GetArticleLookupsForArticle(int articleId) {
            this.articleId = articleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArticleLookupsForArticleResponse", WrapperNamespace="http://dsetzer.27seconds.com/ws/", IsWrapped=true)]
    public partial class GetArticleLookupsForArticle1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dsetzer.27seconds.com/ws/", Order=0)]
        public WCFTestApp.ServiceReference1.ArrayOfXElement GetArticleLookupsForArticleResult;
        
        public GetArticleLookupsForArticle1() {
        }
        
        public GetArticleLookupsForArticle1(WCFTestApp.ServiceReference1.ArrayOfXElement GetArticleLookupsForArticleResult) {
            this.GetArticleLookupsForArticleResult = GetArticleLookupsForArticleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArticlesSoapChannel : WCFTestApp.ServiceReference1.ArticlesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFTestApp.ServiceReference1.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFTestApp.ServiceReference1.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchArticlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchArticlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFTestApp.ServiceReference1.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFTestApp.ServiceReference1.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RateArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFTestApp.ServiceReference1.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFTestApp.ServiceReference1.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateArticle1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RateArticle1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFTestApp.ServiceReference1.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFTestApp.ServiceReference1.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetArticleLookupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetArticleLookupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFTestApp.ServiceReference1.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFTestApp.ServiceReference1.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetArticleLookups1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetArticleLookups1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFTestApp.ServiceReference1.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFTestApp.ServiceReference1.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticlesSoapClient : System.ServiceModel.ClientBase<WCFTestApp.ServiceReference1.ArticlesSoap>, WCFTestApp.ServiceReference1.ArticlesSoap {
        
        private BeginOperationDelegate onBeginGetArticleDelegate;
        
        private EndOperationDelegate onEndGetArticleDelegate;
        
        private System.Threading.SendOrPostCallback onGetArticleCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchArticlesDelegate;
        
        private EndOperationDelegate onEndSearchArticlesDelegate;
        
        private System.Threading.SendOrPostCallback onSearchArticlesCompletedDelegate;
        
        private BeginOperationDelegate onBeginRateArticleDelegate;
        
        private EndOperationDelegate onEndRateArticleDelegate;
        
        private System.Threading.SendOrPostCallback onRateArticleCompletedDelegate;
        
        private BeginOperationDelegate onBeginRateArticle1Delegate;
        
        private EndOperationDelegate onEndRateArticle1Delegate;
        
        private System.Threading.SendOrPostCallback onRateArticle1CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetArticleLookupsDelegate;
        
        private EndOperationDelegate onEndGetArticleLookupsDelegate;
        
        private System.Threading.SendOrPostCallback onGetArticleLookupsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetArticleLookups1Delegate;
        
        private EndOperationDelegate onEndGetArticleLookups1Delegate;
        
        private System.Threading.SendOrPostCallback onGetArticleLookups1CompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ArticlesSoapClient() {
        }
        
        public ArticlesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticlesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticlesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticlesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetArticleCompletedEventArgs> GetArticleCompleted;
        
        public event System.EventHandler<SearchArticlesCompletedEventArgs> SearchArticlesCompleted;
        
        public event System.EventHandler<RateArticleCompletedEventArgs> RateArticleCompleted;
        
        public event System.EventHandler<RateArticle1CompletedEventArgs> RateArticle1Completed;
        
        public event System.EventHandler<GetArticleLookupsCompletedEventArgs> GetArticleLookupsCompleted;
        
        public event System.EventHandler<GetArticleLookups1CompletedEventArgs> GetArticleLookups1Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WCFTestApp.ServiceReference1.ArticlesSoap.BeginGetArticle(int articleId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetArticle(articleId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestApp.ServiceReference1.ArrayOfXElement WCFTestApp.ServiceReference1.ArticlesSoap.EndGetArticle(System.IAsyncResult result) {
            return base.Channel.EndGetArticle(result);
        }
        
        private System.IAsyncResult OnBeginGetArticle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int articleId = ((int)(inValues[0]));
            return ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).BeginGetArticle(articleId, callback, asyncState);
        }
        
        private object[] OnEndGetArticle(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.ArrayOfXElement retVal = ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).EndGetArticle(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetArticleCompleted(object state) {
            if ((this.GetArticleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetArticleCompleted(this, new GetArticleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetArticleAsync(int articleId) {
            this.GetArticleAsync(articleId, null);
        }
        
        public void GetArticleAsync(int articleId, object userState) {
            if ((this.onBeginGetArticleDelegate == null)) {
                this.onBeginGetArticleDelegate = new BeginOperationDelegate(this.OnBeginGetArticle);
            }
            if ((this.onEndGetArticleDelegate == null)) {
                this.onEndGetArticleDelegate = new EndOperationDelegate(this.OnEndGetArticle);
            }
            if ((this.onGetArticleCompletedDelegate == null)) {
                this.onGetArticleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetArticleCompleted);
            }
            base.InvokeAsync(this.onBeginGetArticleDelegate, new object[] {
                        articleId}, this.onEndGetArticleDelegate, this.onGetArticleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WCFTestApp.ServiceReference1.ArticlesSoap.BeginSearchArticles(object[] authorId, object[] articleApplicable, string articleTitle, string articleSummary, object[] articleKeywords, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchArticles(authorId, articleApplicable, articleTitle, articleSummary, articleKeywords, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestApp.ServiceReference1.ArrayOfXElement WCFTestApp.ServiceReference1.ArticlesSoap.EndSearchArticles(System.IAsyncResult result) {
            return base.Channel.EndSearchArticles(result);
        }
        
        private System.IAsyncResult OnBeginSearchArticles(object[] inValues, System.AsyncCallback callback, object asyncState) {
            object[] authorId = ((object[])(inValues[0]));
            object[] articleApplicable = ((object[])(inValues[1]));
            string articleTitle = ((string)(inValues[2]));
            string articleSummary = ((string)(inValues[3]));
            object[] articleKeywords = ((object[])(inValues[4]));
            return ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).BeginSearchArticles(authorId, articleApplicable, articleTitle, articleSummary, articleKeywords, callback, asyncState);
        }
        
        private object[] OnEndSearchArticles(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.ArrayOfXElement retVal = ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).EndSearchArticles(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchArticlesCompleted(object state) {
            if ((this.SearchArticlesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchArticlesCompleted(this, new SearchArticlesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchArticlesAsync(object[] authorId, object[] articleApplicable, string articleTitle, string articleSummary, object[] articleKeywords) {
            this.SearchArticlesAsync(authorId, articleApplicable, articleTitle, articleSummary, articleKeywords, null);
        }
        
        public void SearchArticlesAsync(object[] authorId, object[] articleApplicable, string articleTitle, string articleSummary, object[] articleKeywords, object userState) {
            if ((this.onBeginSearchArticlesDelegate == null)) {
                this.onBeginSearchArticlesDelegate = new BeginOperationDelegate(this.OnBeginSearchArticles);
            }
            if ((this.onEndSearchArticlesDelegate == null)) {
                this.onEndSearchArticlesDelegate = new EndOperationDelegate(this.OnEndSearchArticles);
            }
            if ((this.onSearchArticlesCompletedDelegate == null)) {
                this.onSearchArticlesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchArticlesCompleted);
            }
            base.InvokeAsync(this.onBeginSearchArticlesDelegate, new object[] {
                        authorId,
                        articleApplicable,
                        articleTitle,
                        articleSummary,
                        articleKeywords}, this.onEndSearchArticlesDelegate, this.onSearchArticlesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WCFTestApp.ServiceReference1.ArticlesSoap.BeginRateArticle(int articleId, int rating, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRateArticle(articleId, rating, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestApp.ServiceReference1.ArrayOfXElement WCFTestApp.ServiceReference1.ArticlesSoap.EndRateArticle(System.IAsyncResult result) {
            return base.Channel.EndRateArticle(result);
        }
        
        private System.IAsyncResult OnBeginRateArticle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int articleId = ((int)(inValues[0]));
            int rating = ((int)(inValues[1]));
            return ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).BeginRateArticle(articleId, rating, callback, asyncState);
        }
        
        private object[] OnEndRateArticle(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.ArrayOfXElement retVal = ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).EndRateArticle(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRateArticleCompleted(object state) {
            if ((this.RateArticleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RateArticleCompleted(this, new RateArticleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RateArticleAsync(int articleId, int rating) {
            this.RateArticleAsync(articleId, rating, null);
        }
        
        public void RateArticleAsync(int articleId, int rating, object userState) {
            if ((this.onBeginRateArticleDelegate == null)) {
                this.onBeginRateArticleDelegate = new BeginOperationDelegate(this.OnBeginRateArticle);
            }
            if ((this.onEndRateArticleDelegate == null)) {
                this.onEndRateArticleDelegate = new EndOperationDelegate(this.OnEndRateArticle);
            }
            if ((this.onRateArticleCompletedDelegate == null)) {
                this.onRateArticleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRateArticleCompleted);
            }
            base.InvokeAsync(this.onBeginRateArticleDelegate, new object[] {
                        articleId,
                        rating}, this.onEndRateArticleDelegate, this.onRateArticleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WCFTestApp.ServiceReference1.ArticlesSoap.BeginRateArticle1(WCFTestApp.ServiceReference1.RateArticleWithComments request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRateArticle1(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRateArticle1(int articleId, int rating, string comments, System.AsyncCallback callback, object asyncState) {
            WCFTestApp.ServiceReference1.RateArticleWithComments inValue = new WCFTestApp.ServiceReference1.RateArticleWithComments();
            inValue.articleId = articleId;
            inValue.rating = rating;
            inValue.comments = comments;
            return ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).BeginRateArticle1(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestApp.ServiceReference1.RateArticleWithComments1 WCFTestApp.ServiceReference1.ArticlesSoap.EndRateArticle1(System.IAsyncResult result) {
            return base.Channel.EndRateArticle1(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private WCFTestApp.ServiceReference1.ArrayOfXElement EndRateArticle1(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.RateArticleWithComments1 retVal = ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).EndRateArticle1(result);
            return retVal.RateArticleWithCommentsResult;
        }
        
        private System.IAsyncResult OnBeginRateArticle1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int articleId = ((int)(inValues[0]));
            int rating = ((int)(inValues[1]));
            string comments = ((string)(inValues[2]));
            return this.BeginRateArticle1(articleId, rating, comments, callback, asyncState);
        }
        
        private object[] OnEndRateArticle1(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.ArrayOfXElement retVal = this.EndRateArticle1(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRateArticle1Completed(object state) {
            if ((this.RateArticle1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RateArticle1Completed(this, new RateArticle1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RateArticle1Async(int articleId, int rating, string comments) {
            this.RateArticle1Async(articleId, rating, comments, null);
        }
        
        public void RateArticle1Async(int articleId, int rating, string comments, object userState) {
            if ((this.onBeginRateArticle1Delegate == null)) {
                this.onBeginRateArticle1Delegate = new BeginOperationDelegate(this.OnBeginRateArticle1);
            }
            if ((this.onEndRateArticle1Delegate == null)) {
                this.onEndRateArticle1Delegate = new EndOperationDelegate(this.OnEndRateArticle1);
            }
            if ((this.onRateArticle1CompletedDelegate == null)) {
                this.onRateArticle1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRateArticle1Completed);
            }
            base.InvokeAsync(this.onBeginRateArticle1Delegate, new object[] {
                        articleId,
                        rating,
                        comments}, this.onEndRateArticle1Delegate, this.onRateArticle1CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WCFTestApp.ServiceReference1.ArticlesSoap.BeginGetArticleLookups(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetArticleLookups(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestApp.ServiceReference1.ArrayOfXElement WCFTestApp.ServiceReference1.ArticlesSoap.EndGetArticleLookups(System.IAsyncResult result) {
            return base.Channel.EndGetArticleLookups(result);
        }
        
        private System.IAsyncResult OnBeginGetArticleLookups(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).BeginGetArticleLookups(callback, asyncState);
        }
        
        private object[] OnEndGetArticleLookups(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.ArrayOfXElement retVal = ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).EndGetArticleLookups(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetArticleLookupsCompleted(object state) {
            if ((this.GetArticleLookupsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetArticleLookupsCompleted(this, new GetArticleLookupsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetArticleLookupsAsync() {
            this.GetArticleLookupsAsync(null);
        }
        
        public void GetArticleLookupsAsync(object userState) {
            if ((this.onBeginGetArticleLookupsDelegate == null)) {
                this.onBeginGetArticleLookupsDelegate = new BeginOperationDelegate(this.OnBeginGetArticleLookups);
            }
            if ((this.onEndGetArticleLookupsDelegate == null)) {
                this.onEndGetArticleLookupsDelegate = new EndOperationDelegate(this.OnEndGetArticleLookups);
            }
            if ((this.onGetArticleLookupsCompletedDelegate == null)) {
                this.onGetArticleLookupsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetArticleLookupsCompleted);
            }
            base.InvokeAsync(this.onBeginGetArticleLookupsDelegate, null, this.onEndGetArticleLookupsDelegate, this.onGetArticleLookupsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WCFTestApp.ServiceReference1.ArticlesSoap.BeginGetArticleLookups1(WCFTestApp.ServiceReference1.GetArticleLookupsForArticle request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetArticleLookups1(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetArticleLookups1(int articleId, System.AsyncCallback callback, object asyncState) {
            WCFTestApp.ServiceReference1.GetArticleLookupsForArticle inValue = new WCFTestApp.ServiceReference1.GetArticleLookupsForArticle();
            inValue.articleId = articleId;
            return ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).BeginGetArticleLookups1(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestApp.ServiceReference1.GetArticleLookupsForArticle1 WCFTestApp.ServiceReference1.ArticlesSoap.EndGetArticleLookups1(System.IAsyncResult result) {
            return base.Channel.EndGetArticleLookups1(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private WCFTestApp.ServiceReference1.ArrayOfXElement EndGetArticleLookups1(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.GetArticleLookupsForArticle1 retVal = ((WCFTestApp.ServiceReference1.ArticlesSoap)(this)).EndGetArticleLookups1(result);
            return retVal.GetArticleLookupsForArticleResult;
        }
        
        private System.IAsyncResult OnBeginGetArticleLookups1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int articleId = ((int)(inValues[0]));
            return this.BeginGetArticleLookups1(articleId, callback, asyncState);
        }
        
        private object[] OnEndGetArticleLookups1(System.IAsyncResult result) {
            WCFTestApp.ServiceReference1.ArrayOfXElement retVal = this.EndGetArticleLookups1(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetArticleLookups1Completed(object state) {
            if ((this.GetArticleLookups1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetArticleLookups1Completed(this, new GetArticleLookups1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetArticleLookups1Async(int articleId) {
            this.GetArticleLookups1Async(articleId, null);
        }
        
        public void GetArticleLookups1Async(int articleId, object userState) {
            if ((this.onBeginGetArticleLookups1Delegate == null)) {
                this.onBeginGetArticleLookups1Delegate = new BeginOperationDelegate(this.OnBeginGetArticleLookups1);
            }
            if ((this.onEndGetArticleLookups1Delegate == null)) {
                this.onEndGetArticleLookups1Delegate = new EndOperationDelegate(this.OnEndGetArticleLookups1);
            }
            if ((this.onGetArticleLookups1CompletedDelegate == null)) {
                this.onGetArticleLookups1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetArticleLookups1Completed);
            }
            base.InvokeAsync(this.onBeginGetArticleLookups1Delegate, new object[] {
                        articleId}, this.onEndGetArticleLookups1Delegate, this.onGetArticleLookups1CompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WCFTestApp.ServiceReference1.ArticlesSoap CreateChannel() {
            return new ArticlesSoapClientChannel(this);
        }
        
        private class ArticlesSoapClientChannel : ChannelBase<WCFTestApp.ServiceReference1.ArticlesSoap>, WCFTestApp.ServiceReference1.ArticlesSoap {
            
            public ArticlesSoapClientChannel(System.ServiceModel.ClientBase<WCFTestApp.ServiceReference1.ArticlesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetArticle(int articleId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = articleId;
                System.IAsyncResult _result = base.BeginInvoke("GetArticle", _args, callback, asyncState);
                return _result;
            }
            
            public WCFTestApp.ServiceReference1.ArrayOfXElement EndGetArticle(System.IAsyncResult result) {
                object[] _args = new object[0];
                WCFTestApp.ServiceReference1.ArrayOfXElement _result = ((WCFTestApp.ServiceReference1.ArrayOfXElement)(base.EndInvoke("GetArticle", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearchArticles(object[] authorId, object[] articleApplicable, string articleTitle, string articleSummary, object[] articleKeywords, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = authorId;
                _args[1] = articleApplicable;
                _args[2] = articleTitle;
                _args[3] = articleSummary;
                _args[4] = articleKeywords;
                System.IAsyncResult _result = base.BeginInvoke("SearchArticles", _args, callback, asyncState);
                return _result;
            }
            
            public WCFTestApp.ServiceReference1.ArrayOfXElement EndSearchArticles(System.IAsyncResult result) {
                object[] _args = new object[0];
                WCFTestApp.ServiceReference1.ArrayOfXElement _result = ((WCFTestApp.ServiceReference1.ArrayOfXElement)(base.EndInvoke("SearchArticles", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRateArticle(int articleId, int rating, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = articleId;
                _args[1] = rating;
                System.IAsyncResult _result = base.BeginInvoke("RateArticle", _args, callback, asyncState);
                return _result;
            }
            
            public WCFTestApp.ServiceReference1.ArrayOfXElement EndRateArticle(System.IAsyncResult result) {
                object[] _args = new object[0];
                WCFTestApp.ServiceReference1.ArrayOfXElement _result = ((WCFTestApp.ServiceReference1.ArrayOfXElement)(base.EndInvoke("RateArticle", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRateArticle1(WCFTestApp.ServiceReference1.RateArticleWithComments request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("RateArticle1", _args, callback, asyncState);
                return _result;
            }
            
            public WCFTestApp.ServiceReference1.RateArticleWithComments1 EndRateArticle1(System.IAsyncResult result) {
                object[] _args = new object[0];
                WCFTestApp.ServiceReference1.RateArticleWithComments1 _result = ((WCFTestApp.ServiceReference1.RateArticleWithComments1)(base.EndInvoke("RateArticle1", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetArticleLookups(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetArticleLookups", _args, callback, asyncState);
                return _result;
            }
            
            public WCFTestApp.ServiceReference1.ArrayOfXElement EndGetArticleLookups(System.IAsyncResult result) {
                object[] _args = new object[0];
                WCFTestApp.ServiceReference1.ArrayOfXElement _result = ((WCFTestApp.ServiceReference1.ArrayOfXElement)(base.EndInvoke("GetArticleLookups", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetArticleLookups1(WCFTestApp.ServiceReference1.GetArticleLookupsForArticle request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetArticleLookups1", _args, callback, asyncState);
                return _result;
            }
            
            public WCFTestApp.ServiceReference1.GetArticleLookupsForArticle1 EndGetArticleLookups1(System.IAsyncResult result) {
                object[] _args = new object[0];
                WCFTestApp.ServiceReference1.GetArticleLookupsForArticle1 _result = ((WCFTestApp.ServiceReference1.GetArticleLookupsForArticle1)(base.EndInvoke("GetArticleLookups1", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.Phone.ServiceReference", "3.7.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
